# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: stageCompilePackage
  displayName: 'Compile and publish package'
  jobs:
  - job: jobProcessingContent
    displayName: 'Processing iobroker.homebrain content'
    pool:
      name: Default
    steps:
    - task: GitVersion@5
      inputs:
        runtime: 'core'
