trigger:
  branches:
    include:
    - feature/preparation

stages:
- stage: stageCompilePackage
  displayName: 'Compile and test package'
  jobs:
  - job: jobProcessingContent
    displayName: 'Processing iobroker.fa365 content'
    pool:
      name: Default
    steps:
    - task: GitVersion@5
      inputs:
        runtime: 'core'

