trigger:
  branches:
    include:
    - master

stages:
- stage: stageCompilePackage
  displayName: 'Compile and test package'
  jobs:
  - job: jobProcessingContent
    displayName: 'Processing iobroker.fa365 content'
    pool:
      name: Default
    steps:
    - task: GitVersion@5
      inputs:
        runtime: 'core'
    - task: replacetokens@3
      inputs:
        rootDirectory: '$(Build.Repository.LocalPath)'
        targetFiles: |
          **/io-package.json
          **/package.json
        encoding: 'auto'
        writeBOM: true
        escapeType: 'json'
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(Build.Repository.LocalPath)'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
        workingDir: '$(Build.Repository.LocalPath)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.Repository.LocalPath)'
        Contents: |
          io-package.json
          package.json
          README.md
          admin/**/*
          build/**/*
        TargetFolder: '$(Build.BinariesDirectory)'
        CleanTargetFolder: true
        OverWrite: true
        preserveTimestamp: true
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'pack'
        workingDir: '$(Build.BinariesDirectory)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.BinariesDirectory)'
        Contents: |
          *.tgz
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
        OverWrite: true
        preserveTimestamp: true
    - task: FtpUpload@2
      inputs:
        credentialsOption: 'serviceEndpoint'
        serverEndpoint: 'ftp_iob'
        rootDirectory: '$(Build.ArtifactStagingDirectory)'
        filePatterns: '**'
        remoteDirectory: '/ftp_upload'
        enableUtf8: true
        clean: false
        cleanContents: false
        preservePaths: false
        trustSSL: true
