trigger:
  branches:
    include:
    - master

stages:
- stage: stageCompilePackage
  displayName: 'Compile and test package'
  jobs:
  - job: jobProcessingContent
    displayName: 'Processing iobroker.fa365 content'
    pool:
      name: Default
    steps:
    - task: GitVersion@5
      inputs:
        runtime: 'core'
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(Build.Repository.LocalPath)'
    - task: replacetokens@3
      inputs:
        rootDirectory: '$(Build.Repository.LocalPath)'
        targetFiles: |
          **/io-package.json
          **/package.json
        encoding: 'auto'
        writeBOM: true
        escapeType: 'json'
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.Repository.LocalPath)'
        Contents: |
          /io-package.json
          /package.json
          /readme.md
          /admin/**/*
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
        OverWrite: true
        preserveTimestamp: true

